In [1]:
%cd ~/SSMuLA

/disk2/fli/SSMuLA

In [2]:
%load_ext autoreload
%autoreload 2
%load_ext blackcellmagic

In [3]:
import pandas as pd

In [14]:
t7_zs = pd.read_csv("results/zs_comb_5/none/scale2max/all/T7.csv")
t7_zs

,AAs,AA1_x,AA2_x,AA3_x,fitness,active,muts,n_mut,ed_score,ed_rank,...,msanoif-comb_score,structnmsa-comb_score,two-best_score,Triad-ev_rank,Triad-esm_rank,struc-comb_rank,msa-comb_rank,msanoif-comb_rank,structnmsa-comb_rank,two-best_rank
0,HTY,H,T,Y,0.0,False,N748H:R756T:Q758Y,3,-3,3807.0,...,-4811.0,-8142.0,-3300.0,443.0,1841.0,756.0,1805.0,2116.5,1105.5,1334.0
1,WNG,W,N,G,0.0,False,N748W:R756N:Q758G,3,-3,3807.0,...,-9706.5,-18051.5,-9940.5,4378.0,4795.5,4957.0,5477.0,5100.5,5334.0,5284.0
2,QAM,Q,A,M,0.0,False,N748Q:R756A:Q758M,3,-3,3807.0,...,-5125.0,-8466.0,-3672.0,1277.0,1778.5,765.0,1732.0,2295.0,1231.0,1531.0
3,WMA,W,M,A,0.0,False,N748W:R756M:Q758A,3,-3,3807.0,...,-10715.0,-16537.0,-11033.0,4280.5,2469.0,3027.5,5623.0,5716.0,4840.0,5880.0
4,PPV,P,P,V,0.0,False,N748P:R756P:Q758V,3,-3,3807.0,...,-12180.0,-25512.0,-12646.0,6616.0,6647.0,6700.0,6576.0,6383.5,6655.0,6564.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6720,SVR,S,V,R,0.0,False,N748S:R756V:Q758R,3,-3,3807.0,...,-3381.0,-8099.0,-2402.0,2983.0,2650.0,1848.0,783.0,1426.5,1083.0,844.0
6721,QMI,Q,M,I,0.0,False,N748Q:R756M:Q758I,3,-3,3807.0,...,-7051.0,-12408.0,-8749.0,2427.5,864.0,2494.0,3940.0,3467.5,3178.0,4596.0
6722,LFS,L,F,S,0.0,False,N748L:R756F:Q758S,3,-3,3807.0,...,-5402.0,-7712.0,-4635.0,567.0,544.0,231.0,2102.0,2474.5,927.0,2103.0
6723,NSM,N,S,M,0.0,False,R756S:Q758M,2,-2,466.0,...,-1343.0,-4998.0,-2057.0,604.0,482.0,975.0,366.0,545.5,209.5,671.0
6724,TPR,T,P,R,0.0,False,N748T:R756P:Q758R,3,-3,3807.0,...,-4121.0,-15909.0,-7857.0,5108.5,4765.0,6034.0,3293.5,1760.0,4611.0,4054.5

In [15]:
t7_zs.columns

Index(['AAs', 'AA1_x', 'AA2_x', 'AA3_x', 'fitness', 'active', 'muts', 'n_mut',
       'ed_score', 'ed_rank', 'AA1_y', 'AA2_y', 'AA3_y', 'seq', 'pos',
       'esm_score', 'ev_score', 'esm_rank', 'ev_rank', 'esmif_score',
       'esmif_rank', 'Triad_score', 'Triad_rank', 'coves_score', 'coves_rank',
       'Triad-ev_score', 'Triad-esm_score', 'struc-comb_score',
       'msa-comb_score', 'msanoif-comb_score', 'structnmsa-comb_score',
       'two-best_score', 'Triad-ev_rank', 'Triad-esm_rank', 'struc-comb_rank',
       'msa-comb_rank', 'msanoif-comb_rank', 'structnmsa-comb_rank',
       'two-best_rank'],
      dtype='object')

In [16]:
t7_zs[["AAs", "fitness", "ed_score", "esm_score", "ev_score", "Triad_score", "coves_score"]].isna()

        AAs  fitness  ed_score  esm_score  ev_score  Triad_score  coves_score
0     False    False     False      False     False        False        False
1     False    False     False      False     False        False        False
2     False    False     False      False     False        False        False
3     False    False     False      False     False        False        False
4     False    False     False      False     False        False        False
...     ...      ...       ...        ...       ...          ...          ...
6720  False    False     False      False     False        False        False
6721  False    False     False      False     False        False        False
6722  False    False     False      False     False        False        False
6723  False    False     False      False     False        False        False
6724  False    False     False      False     False        False        False

[6725 rows x 7 columns]

In [20]:
t7_zs[t7_zs[["AAs", "fitness", "ed_score", "esm_score", "ev_score", "Triad_score", "coves_score"]].isna().any(axis=1)]

Empty DataFrame
Columns: [AAs, AA1_x, AA2_x, AA3_x, fitness, active, muts, n_mut, ed_score, ed_rank, AA1_y, AA2_y, AA3_y, seq, pos, esm_score, ev_score, esm_rank, ev_rank, esmif_score, esmif_rank, Triad_score, Triad_rank, coves_score, coves_rank, Triad-ev_score, Triad-esm_score, struc-comb_score, msa-comb_score, msanoif-comb_score, structnmsa-comb_score, two-best_score, Triad-ev_rank, Triad-esm_rank, struc-comb_rank, msa-comb_rank, msanoif-comb_rank, structnmsa-comb_rank, two-best_rank]
Index: []

[0 rows x 39 columns]